version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
      - MSSQL_PID=Developer